oemof/tespy

tespy/components/subsystems.py
I updated the logic for subsystems to allow attributes that are of type str and ditched duplicate call of the set_comps/set_conns methods.
=> improved subsystem __init__ and set_attr logic

tespy/components/components.py, tespy/connections.py, tespy/network_reader.py, tespy/networks.py, tespy/tools/helpers.py, tests/error_tests.py
Add functionality for setting subcooling oder superheating temperature. With this feature you are able to specify the temperature difference to boiling point (`Td_bp`). I have added an example code:
```
nw = nwk.network(['water', 'air'], T_unit='C', p_unit='bar', h_unit='kJ / kg')
so = cmp.source('so')
si = cmp.sink('si')
c = con.connection(so, 'out1', si, 'in1')
nw.add_conns(c)
c.set_attr(p=1, fluid={'water': 1, 'air': 0}, m=5, Td_bp=-5) # temperature is 5 K below boiling point
nw.solve('design')
nw.print_results()
c.set_attr(p=1, fluid={'water': 1, 'air': 0}, m=5, Td_bp=5) # temperature is 5 K above boiling point
nw.solve('design')
nw.print_results()
```
resolve #65
=> functionality for subcooling and superheating

doc/getting_started/tutorial_combustion_chamber.rst, doc/using_tespy.rst, doc/whats_new/v0-1-2.rst, tespy/components/components.py, tespy/networks.py, tests/error_tests.py
The combustion chamber and cogeneration unit should work with a mix of different fuels and not only one specific fuel. The keyword argument fuel will be deprecated as the component will automatically recognize available fuels in the incoming mass flows. Still to do:
Resolve #77 
Resolve #76
=> Make combustion more flexible

doc/whats_new.rst, doc/whats_new/v0-1-3.rst, tespy/components/components.py, tespy/components/subsystems.py, tespy/connections.py, tespy/network_reader.py, tespy/networks.py, tespy/tools/helpers.py, tests/component_tests.py, tests/error_tests.py, tests/heat_pump_test.py
This PR will allow to have separate design cases for different parts of your network.
E. g. using a extraction steam turbine, the back pressure turbine part and the condenser can be designed for no extraction while the extraction condenser is designed for full extraction.
Other changes:
- documentation updates
- new feature T0 (starting value) for fluid property functions using fluid mixtures (fast root finding)
- code realignment for PEP
TODO:
Missing tests:
- specification of design_path
error test for wrong specification
- specification of design_path
error test for wrong specification
-  specification of Q
- specification on bus in offdesign
- error test for wrong bus parameter in bus derivatives
- Q as variable
- negative terminal temperature differences
- error test for missing …
=> Make offdesign calculation more flexible

doc/whats_new/v0-2-0.rst, tespy/components/__init__.py, tespy/components/basics.py, tespy/components/combustion.py, tespy/components/heat_exchangers.py, tespy/components/nodes.py, tespy/components/piping.py, tespy/components/reactors.py, tespy/components/subsystems.py, tespy/components/turbomachinery.py, tespy/connections.py, tespy/networks/__init__.py, tespy/networks/network_reader.py, tespy/networks/networks.py, tests/error_tests.py
I added shortcuts for tespy.components and tespy.networks imports, e. g.:
```
from tespy.components import sink, source, turbine, heat_exchanger
from tespy.networks import network, load_network
```
Note: The load_nwk method was renamed to load_network for clarity!
=> Add import shortcuts

doc/whats_new/v0-2-0.rst, tespy/components/combustion.py, tespy/networks/networks.py
The solver will specify all connections attached to component
inlets and outlets that are used at least twice.
=> Improve the network topology debugging

.travis.yml, tespy/__init__.py
Replace python 3.5 with 3.6 and add 3.8.
=> Add python 3.6 and 3.8 support for software tests

tespy/components/heat_exchangers.py
This PR fixes links in the docstrings and prevents calculation of heat losses of the solar collector if the energy group parameter is not used.
=> Fix solar collector in heat_exchangers.py

doc/whats_new/v0-2-1.rst, setup.py, tespy/components/basics.py, tespy/components/combustion.py, tespy/components/components.py, tespy/components/heat_exchangers.py, tespy/components/nodes.py, tespy/components/piping.py, tespy/components/reactors.py, tespy/components/turbomachinery.py, tespy/connections.py, tespy/tools/data_containers.py, tests/component_tests/turbomachinery_tests.py, tests/error_tests.py
No warning/error is issued, when specifying x, y or x. y, z1 and z2 values for the datacontainers although these data are not used in any way.
=> Remove deprecated fields for characteristics data containers

doc/tespy_modules/networks.rst, doc/whats_new/v0-2-2.rst, tespy/components/combustion.py, tespy/components/heat_exchangers.py, tespy/components/turbomachinery.py, tespy/networks/networks.py, tests/component_tests/turbomachinery_tests.py
This PR allows an initialisation from the previous calculation without saving the results and reloading them. This should save a considerable amount of time.
Additionally, the component test of the compressor regarding the compressor map was bugged (pressure ratio < 1 in some offdesign cases). This has been fixed.
=> Initialise calculation from previous calculation

tespy/components/components.py
In the component parameter checks after calculation, warning messages are triggered, when the result is expected to be at the minimum or the maximum value but has floating point numbers at the very end. For example, if the pressure ratio of a valve is higher than 1 a warning is prompted. Specifying the value of 1 might yield an actual value of 1.0000000000000001 or similar. In this case no warning should be displayed.
=> Fix warning logging: Avoid messages due to bad rounding

tespy/networks/networks.py
Resolve #188 
This fix resolves ZeroDivisionErrors which occur in the calculation of iterations per second. When division by zero occurs the iterations per second are set to their limit of infinity.
=> Fix ZeroDivisionError in iteration speed calculation

doc/tespy_modules/components.rst, doc/whats_new/v0-3-0.rst, tespy/components/basics.py, tespy/components/combustion.py, tespy/components/customs.py, tespy/components/heat_exchangers.py, tespy/components/nodes.py, tespy/components/piping.py, tespy/components/reactors.py, tespy/components/turbomachinery.py, tespy/connections.py, tests/test_components/test_heat_exchangers.py, tests/test_models/test_heat_pump_model.py
Using `kA` as offdesign parameter is counter-intuitive as it suggests a constant value for kA in offdesign. At the moment, this is not the case, instead, kA follows a characteristic line. Therefore, the parameter `kA` is renamed to `kA_char` and a new parameter `kA` is implemented. The new parameter `kA` will be constant in case it is an offdesign parameter. A warning will be printed to the user, that this behavior has changed.
=> Heat exchanger parameter adjusting: Rename kA to kA_char and add kA as independent parameter

tespy/connections.py
As manipulations to the values of a dictionary containing the fluid composition of connections are performed, somewhat unpredictable issues/behavior will appear, if the same dictionary is passed multiple times. To avoid this issue, the connection will receive copies of the dictionary instead.
=> Passing dictionaries as connection parameters may cause trouble

doc/tespy_modules/networks.rst, doc/tutorials_examples/tutorial_combustion_chamber.rst, doc/whats_new/v0-3-0.rst, tespy/components/combustion.py, tespy/components/heat_exchangers.py, tespy/networks/network_reader.py, tespy/networks/networks.py, tespy/tools/fluid_properties.py, tests/test_errors.py
The minimum value for temperature will be selected as maximum of the given minimum temperature levels of the fluid property database within the specified fluid mixture. This ensures, that T_mix_ph and T_mix_ps calls on mixtures do not fail due to temperature limit restrictions. At the same time, there must be a check, if the newton algorithm actually found a valid value for T. Additionally, the parameter T_range will be deprecated by this feature.
=> Improve stability: Add minimum value restriction for temperature in fluid property functions

docs/whats_new/v0-3-5.rst, src/tespy/networks/networks.py, tests/test_components/test_turbomachinery.py, tests/test_errors.py
- checking fluid vector for fluids not within the network's fluid list
- added 'def test_bad_fluids_in_fluid_vector' in 'test_errors.py'
- resolve #232
=> checking fluid vector for fluids not within the network's fluid list

docs/whats_new/v0-4-1.rst, src/tespy/components/combustion/combustion_chamber_stoich.py
**General**
Describe your pull request as transparent as possible:
* What functionality does it implement? Bug Fix
* Where is it located? 
Location: [Combustion Chamber Stoich](https://github.com/oemof/tespy/blob/dev/src/tespy/components/combustion/combustion_chamber.py)
* Which bugs are fixed
Received an error: "RuntimeError: dictionary keys changed during iteration" for CombustionChamberStoich on the line "for f in self.air.val.keys():" which can be mitigated by adding a **list casting** similar to one on line 260 for the fuel
* Are there related issues? No
=> #Line 253 combustion chamber stoich - issue of dict size change during for loop

docs/whats_new/v0-4-3.rst, src/tespy/tools/document_models.py
Adds a information on when the model documentation was generated to the main info table.
=> Add timestamp to automatic model documentation generation

docs/whats_new.rst, docs/whats_new/v0-4-4.rst, setup.py, src/tespy/__init__.py, src/tespy/components/combustion/combustion_chamber.py, src/tespy/components/combustion/combustion_chamber_stoich.py, src/tespy/components/combustion/combustion_engine.py, src/tespy/components/component.py, src/tespy/connections/bus.py, src/tespy/connections/connection.py, src/tespy/networks/network.py, src/tespy/tools/analyses.py, src/tespy/tools/data_containers.py, src/tespy/tools/document_models.py, src/tespy/tools/fluid_properties.py
Checking for keys ins dictionaries should not be done with `in dict.keys()` but with `in dict` instead.
=> Fix: Checking dictionaries for specific keys

docs/whats_new.rst, docs/whats_new/v0-4-4.rst, src/tespy/components/basics/cycle_closer.py, src/tespy/components/heat_exchangers/heat_exchanger_simple.py, src/tespy/components/heat_exchangers/parabolic_trough.py, src/tespy/components/heat_exchangers/solar_collector.py, src/tespy/networks/network.py, src/tespy/tools/data_containers.py, tests/test_components/test_heat_exchangers.py, tests/test_errors.py, tests/test_networks/test_network.py, tests/test_tools/test_characteristics.py
Resolve #276 
The components
- HeatExchangerSimple
- ParabolicTrough
- Pipe
- SolarCollector
are missing results in the results DataFrame, e.g. in case kA is a result of change in temperature in a pipe at specified ambient temperature. The result is available on component level (i.e. comp.kA.val) but not in the network's results DataFrame (i.e. network.results['Pipe']). A new 'is_result' attribute is added to ComponentProperties DataContainers to handle this.
Tests to be added!
=> Fix: Add missing component results in the results DataFrames

docs/whats_new/v0-4-4.rst, src/tespy/components/combustion/combustion_chamber.py
Resolve #272 
This PR adds new fuels to the class CombustionChamber. To check:
- Is the energy balance calculated correctly even for liquid fuels?
- Default starting values for nDodecane are really bad.
=> Add new feature: nDodecane as fuel for combustion

docs/analyses/exergy.rst, docs/tespy_modules/characteristics.rst, docs/tespy_modules/components.rst, docs/whats_new.rst, docs/whats_new/v0-6-1.rst, setup.py, src/tespy/__init__.py
Minor changes to punctuation, grammar, and word order for clarity. Same for exergy, characteristics, and component documentation.
=> minor typos, clarity changes in characteristics and components modules

docs/api/_images/FuelCell.svg, docs/api/tespy.components.rst, docs/tespy_modules/components.rst, docs/whats_new/v0-6-0.rst, src/tespy/components/__init__.py, src/tespy/components/reactors/fuel_cell.py
The code implements a fuel cell as new component. It is designed just like the water electrolyzer, i.e. it produces water out of hydrogen and oxygen with an additional cooling fluid. 
The import of the code is implemented in the components init file, the code itself is located in the folder components/reactors.
=> Add fuel cell draft code

src/tespy/networks/network.py, src/tespy/tools/logger.py
**General**
This PR is a follow-up on #390 - it should be merged after #390 has been integrated.
The main purpose of this PR is to silence stdout when running TESPy. For compatibility reasons, the default settings make the system run as before, but it is now possible to send iteration progress reports via the logging framework. The same is the case for the results. 
Some internal functions have been renamed, but the external interface of TESPy is unchanged. The only noticeable change is that the iteration output now contains a progress indicator.
=> Report progress and results with the logger object

docs/whats_new/v0-6-3.rst, src/tespy/components/heat_exchangers/base.py, src/tespy/components/heat_exchangers/condenser.py, src/tespy/components/heat_exchangers/simple.py, tests/test_components/test_heat_exchangers.py
**General**
Describe your pull request as transparent as possible:
This PR fixes the treatment of heat exchangers with constant temperature difference.
For constant temperature differences the logarithmic mean temperature difference is invalid, as it would result in division by zero.
This simple bugfix just sets the logarithmic mean temperature difference to the constant temperature difference in the case that ttd_u == ttd_l.
I have not changed any documentation
**Testing**
I have not updated any tests
=> Bugfix: Add logic for constant dT heat exchangers

docs/whats_new/v0-6-3.rst, src/tespy/networks/network.py
**General**
This PR fixes a small printing error in the log file. When the user choose a unit for a fluid property, the log file will show the range values in SI unit rather than the user specified one.
More details can be found in the related issue: [https://github.com/oemof/tespy/issues/417](#417) 
No documentation file is affected.
**Testing**
No tests are affected by this change.
=> Change units for fluid properties in log file

pyproject.toml, src/tespy/tools/fluid_properties/wrappers.py
CoolProp recently published version 6.6. The bug concerning incompressible fluid reference temperatures has been resolved on their side, therefore this PR introduces minimum CoolProp version of 6.6 and removes the quickfix in the fluid property wrapper module.
=> Bump up CoolProp dependency and remove incompressible fluid handling quick fix

docs/whats_new.rst, docs/whats_new/v0-7-2.rst, src/tespy/connections/connection.py, tests/test_connections.py
=> Switched sign for value referencing of delta to match docs

docs/modules/ude.rst, src/tespy/components/component.py, src/tespy/tools/helpers.py, tests/test_tools/test_helpers.py
The convergence critereon for the newon helper algorithms needed to be updated to target values equal to zero. In case the target value is zero, the tolerance mode is set to absolute difference now. On top of that the old newton function was removed and now all parts of the code use the `newton_with_kwargs` function.
=> Remove old newton function and use newton_with_kwargs instead

docs/scripts/generate_tespy_data_module.py, src/tespy/networks/network.py, src/tespy/networks/network_reader.py, src/tespy/tools/characteristics.py, tests/test_tools/test_characteristics.py
**General**
When writing JSON data to a file, the `json.dumps` method is used to create a string in JSON format, which is then written to disk with the `write` method of the `file` object. The extra conversion is not necessary, since the `json.dump` method directly writes the data to the file, without the extra step of converting the data to a string. See for example [this comparison on StackOverflow](https://stackoverflow.com/questions/36059194/what-is-the-difference-between-json-dump-and-json-dumps-in-python) or the [json module documentation](https://docs.python.org/3/library/json.html).
=> Improve writing JSON file method.

docs/whats_new/v0-7-5.rst, src/tespy/components/nodes/drum.py
**General**
The `get_plotting_data` method of the `Drum` class only returns one process line connecting the saturated liquid `'out1'` with the saturated vapor `'out2'` so far. This can work sometimes, because the input saturated liquid-vapor mixture falls somewhere between these points, but the desuperheating of the gas `'in2'` is lost and can not be shown. Unfortunately, the `Drum` component does not lend itself to a clear fix that is in line with other components and the general discription of the method. That is, because changing the returned dict to contain one line from `'in1'` to `'out1'` and one from `'in2'` to `'out2'` loses the depiction of the isolation of the saturated vapor from the mixture. Therefore, I propose this solution connecting every inlet to every output and letting …
=> Extend get_plotting_data method of Drum class.

docs/whats_new.rst, docs/whats_new/v0-7-7.rst, pyproject.toml, src/tespy/__init__.py, src/tespy/networks/network_reader.py, tests/test_networks/test_network.py
=> Make the network loader only import valid tespy component class names

docs/whats_new.rst, docs/whats_new/v0-7-9.rst, pyproject.toml, src/tespy/__init__.py, src/tespy/connections/connection.py, src/tespy/networks/network.py, src/tespy/tools/document_models.py, src/tespy/tools/fluid_properties/__init__.py, src/tespy/tools/fluid_properties/functions.py, src/tespy/tools/fluid_properties/wrappers.py, src/tespy/tools/global_vars.py, src/tespy/tools/helpers.py
Ciao @fwitte,
I noticed that the property reporting for `Connections `does not include the vapour quality or the state, hence the overall aim of this pull request is to include them in the table of properties for `Connections`.
I implemented the following changes:
- Aligned the calculation of the vapour quality for the `CoolPropWrapper` with that of the `IAPWSWrapper`. Currently the `CoolPropWrapper` reports a vapour quality of `-1` for all single phase states (irrespective of it being gas or liquid).  With the changes below, the vapour quality is now reported as `0` for liquids and `1` for gases, for subcritical conditions.
- Added a state_ph function to the base `FluidPropertiesWrapper`, the `CoolPropWrapper `and the `IAPWSWrapper`. Unfortunately, I lack expertise with Pyromat and so …
=> Vapour Quality and State Reporting

docs/references.bib, docs/whats_new/v0-7-9.rst, pyproject.toml, src/tespy/components/__init__.py, src/tespy/components/turbomachinery/steam_turbine.py, src/tespy/components/turbomachinery/turbine.py, src/tespy/tools/fluid_properties/wrappers.py, tests/test_components/test_turbomachinery.py
**General**
With this PR I would like to submit a new turbine component, which accounts for wet expansion effects using the empirical Baumann correlation.
The expansion of saturated steam (e.g. geothermal or nuclear power applications) inevitably enters the vapour dome and two-phase effects lead to a reduction in the isentropic efficiency. The empirical Baumann rule effectively corrects the dry isentropic turbine efficiency with the average wetness across the turbine.
* Implementation of the `SteamTurbine` component. I chose to make this a separate component (inheriting from `Turbine`) to avoid confusion - though the `SteamTurbine` behaves exactly like a `Turbine` unless the `eta_dry_s` attribute is set
* Updated the `CoolPropWrapper` `Q_ph` function so that it now returns a meaningful …
=> Steam Turbine with wet expansion

docs/examples.rst
The *heatpumps* dashboard is now available online via the streamlit community cloud. The PR changes the target URL of the examples entry for *heatpumps*.
=> Adjust heatpumps example target url.

docs/examples.rst
For better visibility of *heatpumps*, the url is added to the overview. In addition, the reference to the Github repository of *heatpumps* and the possibility to contribute should also be mentioned.
=> Add heatpumps url and github link to example.rst.

docs/whats_new/v0-9-5.rst, src/tespy/networks/network.py
The mass flow starting value is selected by random in the very first setup of a model. This is usually not a problem, but in some cases leads to non-reproducible errors. This change should fix that.
Resolve #509 
Resolve #519
=> Assign rng based on the connection's label
