- tespy/networks.py
Calculation speed increase was too low, main factor are the fluid properties! Changing the CoolProp interface from PropsSI to abstracstate will most likely have a much higher impact!
This new feature will come up in January!
> removed parallel processing option

- tespy/helpers.py
- tespy/networks.py
- Change the CoolProp-interface from PropsSI to CoolProp.AbstractState
- Change the network handling prior to calculation
> Improve calculation speed

- tespy/networks.py
- tespy/tools/helpers.py
I want to add a function to calculate the vapour mass fraction in post processing for all pure fluids. Please have a look at my suggestion, thank you!
> add function to calculate vapour mass fraction in post processing

- tespy/connections.py
> fix misleading bus parameter specification

- doc/whats_new/v0-1-2.rst
- tespy/networks.py
Fixes a bug in preprocessing regarding components attached to multiple busses and adds printouts for the bus parameters to results.
> Fix bug in bus preprocessing

- doc/using_tespy.rst
- doc/whats_new/v0-1-3.rst
- tespy/components/components.py
- tespy/networks.py
- tespy/tools/helpers.py
- define minimum and maximum values for all component properties
- add warning messages, if properties are out of bounds
- custom bounds still possible
> Add generic component property warning messages

- doc/whats_new/v0-2-0.rst
- tespy/components/heat_exchangers.py
Thank you for your contribution @MarBrandt! Could you update "What's New" in the [appropriate section](https://github.com/oemof/tespy/blob/feature/adding_optical_losses/doc/whats_new/v0-2-0.rst)?
> Add optical efficiency to solar collector

- doc/using_tespy/intro.rst
I changed a few small things in the docu.
Maybe I will add some stuff later.
> Add miner docu changes

- .pep8speaks.yml
- doc/whats_new/v0-2-0.rst
- tespy/connections.py
- tespy/networks/networks.py
Only testing the pep8speaks checker.
> Test the PEP8 checker

- doc/whats_new/v0-2-0.rst
- tespy/components/components.py
- tespy/components/subsystems.py
- tespy/connections.py
- tespy/networks/networks.py
- tests/error_tests.py
> Improve subsystem architecture for easier use

- doc/whats_new/v0-2-0.rst
- tespy/tools/characteristics.py
- tespy/tools/helpers.py
- tespy/tools/logger.py
- tests/error_tests.py
- tests/tools_tests/characteristics_tests.py
This PR adds a function to read custom data from your .tespy folder in your home path.
TODO:
- Define tests
- <del>Update docs</del> Done in #112
> Add place for custom characteristics

- doc/tespy_modules/components.rst
- doc/tespy_modules/networks.rst
- doc/whats_new/v0-2-1.rst
- tespy/components/basics.py
- tespy/components/combustion.py
- tespy/components/components.py
- tespy/components/heat_exchangers.py
- tespy/components/nodes.py
- tespy/components/piping.py
- tespy/components/reactors.py
- tespy/components/turbomachinery.py
- tespy/networks/network_reader.py
- tespy/networks/networks.py
- tespy/tools/fluid_properties.py
- tests/component_tests/turbomachinery_tests.py
- tests/error_tests.py
This PR changes the back end architecture for handing the equations and derivatives calls of the components. Additionally. the evaluation of equations and of the corresponding derivatives is modified: Equations regarding already converged variables will not be evaluated any more (or only every xth iteration), in order to cut calculation time. Therefore, I will add a performance test comparing the dev with this branch.
> Improve handling of component equations and derivatives

- doc/tespy_modules/characteristics.rst
- doc/tespy_modules/components.rst
- doc/tespy_modules/connections.rst
- doc/whats_new/v0-2-2.rst
- tespy/connections.py
- tespy/networks/network_reader.py
- tespy/networks/networks.py
- tespy/tools/characteristics.py
- tests/error_tests.py
- tests/tools_tests/characteristics_tests.py
**General**
Describe your pull request as transparent as possible:
* What functionality does it implement? It implements extrapolation of characteristic lines outside of the bounds of the upper and lower limits
* Where is it located? It is located in characteristics.py
* How does the API look? Unsure
* Which bugs are fixed? False results for characteristic lines outside of the bounds
* Are there related issues? Unsure
Please document all changes and/or new features:
* Update the API documentation - Not yet
* Update the corresponding sections in the online documentation - Not yet
* Add inline comments to your code, if required - Not yet
* Update the corresponding What's New file - Not yet
**Testing**
* Adapt the software tests (including doc-tests), if the PR does affect …
> Add new feature: extrapolation for characteristics

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- tespy/components/basics.py
- tespy/components/combustion.py
- tespy/components/customs.py
- tespy/components/heat_exchangers.py
- tespy/components/nodes.py
- tespy/components/piping.py
- tespy/components/reactors.py
- tespy/components/turbomachinery.py
Update/fix the component parameter lists.
> Update component parameter lists

- doc/tespy_modules/components.rst
- doc/tespy_modules/connections.rst
- doc/tespy_modules/fluid_properties.rst
- doc/whats_new/v0-3-0.rst
- tespy/components/components.py
- tespy/components/customs.py
- tespy/connections.py
- tespy/networks/network_reader.py
- tespy/networks/networks.py
- tests/test_components/test_combustion.py
- tests/test_errors.py
> Add None as possibilty to unset values

- doc/api/_images/droplet_separator.svg
- doc/whats_new/v0-3-0.rst
- tespy/components/__init__.py
- tespy/components/components.py
- tespy/components/nodes.py
- tespy/networks/network_reader.py
- tespy/networks/networks.py
- tespy/tools/fluid_properties.py
This PR introduces a droplet separator. It separates a two phase single fluid into its gas and liquid phase.
> Add new component: Droplet separator

- doc/api/_images/parabolic_trough.svg
- doc/api/_images/solar_collector.svg
- doc/references.bib
- doc/tespy_modules/characteristics.rst
- doc/tespy_modules/components.rst
- doc/whats_new/v0-3-0.rst
- tespy/components/__init__.py
- tespy/components/basics.py
- tespy/components/combustion.py
- tespy/components/customs.py
- tespy/components/heat_exchangers.py
- tespy/components/nodes.py
- tespy/components/piping.py
- tespy/components/reactors.py
- tespy/components/turbomachinery.py
- tespy/networks/network_reader.py
- tespy/networks/networks.py
- tespy/tools/characteristics.py
- tests/test_components/test_heat_exchangers.py
> Add new component: Parabolic Trough

- docs/whats_new/v0-3-2.rst
- src/tespy/networks/networks.py
- src/tespy/tools/global_vars.py
Modifies the result table creation in networks.py using minor changes and colors set values blue and variables red depending on whether is_set or is_var are true. Uses bcolors package.
> Highlight result table information

- docs/tutorials_examples/tutorial_heat_pump.rst
- tutorial/step_2.py
- tutorial/step_3.py
Make adjustments according to #213.
Example has been updated by commit https://github.com/oemof/oemof-examples/commit/743bfebd2ee865ef8260a565b85153a28e56414d.
> Documentation: Improve the heat pump example and tutorial

- docs/tutorials_examples/tutorial_pygmo_optimization.rst
Adding a short description of installation methods for PyGMO using conda and pip.
> Pygmo optimization example added pygmo installation notes 

- docs/tespy_modules/networks.rst
- docs/whats_new.rst
- docs/whats_new/v0-3-5.rst
- setup.py
- src/tespy/__init__.py
- src/tespy/components/heat_exchangers.py
- src/tespy/components/piping.py
- src/tespy/networks/networks.py
> Make results coloring optional

- docs/whats_new.rst
- docs/whats_new/v0-3-5.rst
- setup.py
- src/tespy/__init__.py
- src/tespy/components/heat_exchangers.py
- src/tespy/components/piping.py
Adjust limits for zeta max value and for ks if using HW equation. Value limits are changed for simple heat exchanger and valve.
> Adjust some component value limits

- docs/tespy_modules.rst
- docs/tespy_modules/other.rst
- docs/whats_new/v0-4-1.rst
- src/tespy/components/component.py
- src/tespy/networks/network.py
- src/tespy/tools/document_models.py
- src/tespy/tools/helpers.py
- tests/test_errors.py
This PR introduces generic user defined equations that can be applied within your model.
> New Feature: User defined equations

- docs/tespy_modules/connections.rst
- docs/tespy_modules/networks.rst
- docs/whats_new/v0-4-3.rst
- src/tespy/networks/network.py
Network results (connections, components, busses) are provided in a dictionary containing pandas DataFrames for easier access of the data.
> New Feature: Datastructures for network results

- docs/whats_new/v0-4-3.rst
- src/tespy/components/turbomachinery/compressor.py
> Fix broken links compressor class docs

- docs/whats_new/v0-4-4.rst
- src/tespy/networks/network.py
- src/tespy/tools/fluid_properties.py
Improve warning printouts for missing fluid composition data.
> Fix: Add hints for missing fluid information

- docs/whats_new/v0-5-0.rst
- setup.py
**General**
Describe your pull request as transparent as possible:
* What functionality does it implement?
* Where is it located?
* How does the API look?
* Which bugs are fixed
* Are there related issues?
Please document all changes and/or new features:
* Update the API documentation
* Update the corresponding sections in the online documentation
* Add inline comments to your code, if required
* Update the corresponding What's New file
**Testing**
* Adapt the software tests (including doc-tests), if the PR does affect existing tests
* Add new tests for new features
**Questions and Comments**
You are welcome to ask for help or start a discussion on a feature. We very much appreciate your contribution.
> Lift pandas requirement

- docs/whats_new.rst
- docs/whats_new/v0-5-1.rst
- setup.py
- src/tespy/__init__.py
- src/tespy/networks/network.py
> Fix/#289 LaTeX report wrong connection specs

- docs/whats_new/v0-1-2.rst
- docs/whats_new/v0-2-0.rst
- docs/whats_new/v0-6-0.rst
- src/tespy/tools/fluid_properties.py
- src/tespy/tools/global_vars.py
The unit conversion in global_vars.py for mass flow was fixed.
Resolve #316
> correction of mass flow unit conversion

- docs/whats_new/v0-6-0.rst
- src/tespy/tools/analyses.py
- tests/test_analyses/test_exergy_analysis.py
> Fix bug in component and bus aggregation

- LICENSE
- README.rst
- announcement.html
- docs/_static/images/logo_tespy_mini.svg
- docs/_static/js/custom.js
- docs/advanced/exergy.rst
- docs/api.rst
- docs/basics/district_heating.rst
- docs/basics/gas_turbine.rst
- docs/basics/heat_pump.rst
- docs/basics/intro.rst
- docs/basics/rankine_cycle.rst
- docs/benchmarks.rst
- docs/conf.py
- docs/development/how.rst
- docs/development/what.rst
- docs/examples.rst
- docs/introduction.rst
- docs/modules/characteristics.rst
- docs/modules/components.rst
- docs/modules/connections.rst
- docs/modules/networks.rst
- docs/modules/ude.rst
- docs/requirements.txt
- docs/tutorials.rst
- docs/tutorials/district_heating.rst
- docs/tutorials/heat_pump_exergy.rst
- docs/tutorials/heat_pump_steps.rst
- docs/tutorials/pygmo_optimization.rst
- docs/tutorials/starting_values.rst
The banner includes external html so it can be adjusted flexibly according to current needs without merging all changes to all relevant branches (main/dev).
> Add announcement banner

- src/tespy/components/nodes/drum.py
- tests/test_components/test_drum.py
Test files have to be updated still.
Resolves: #450
> Fix a bug in the drum setup, when the secondary mass flow branch is not linear

- docs/whats_new.rst
- docs/whats_new/v0-7-1.rst
- pyproject.toml
- src/tespy/__init__.py
- src/tespy/components/heat_exchangers/desuperheater.py
- src/tespy/networks/network.py
- src/tespy/tools/fluid_properties/wrappers.py
- tests/test_components/test_combustion.py
- tests/test_components/test_merge.py
- tests/test_components/test_reactors.py
- tutorial/advanced/optimization_example.py
> Fix the mass flow and fluid topology simplification for multiprocessing

- src/tespy/components/combustion/base.py
> Fix lambda calculation

- docs/_static/images/basics/gas_turbine_fuel_composition.svg
- docs/_static/images/basics/gas_turbine_fuel_composition_darkmode.svg
- docs/_static/images/basics/gas_turbine_oxygen.svg
- docs/_static/images/basics/gas_turbine_oxygen_darkmode.svg
- docs/_static/images/basics/gas_turbine_parametric.svg
- docs/_static/images/basics/gas_turbine_parametric_darkmode.svg
- docs/whats_new/v0-7-5.rst
- pyproject.toml
- src/tespy/networks/network.py
- tutorial/basics/gas_turbine.py
The oxygen mass fraction dependency was plotted in backwards direction. Temperature must decrease with increasing flue gas oxygen mass fraction.
> Fix result plot in gas turbine example

- docs/whats_new.rst
- docs/whats_new/v0-7-6.rst
- src/tespy/components/component.py
- src/tespy/components/heat_exchangers/base.py
- src/tespy/components/turbomachinery/compressor.py
- src/tespy/connections/connection.py
- src/tespy/networks/network.py
- tests/test_components/test_heat_exchangers.py
This PR introduces two new equations for the `HeatExchanger` class, i.e. the `eff_cold` and `eff_hot` equations, that describe the heat exchanger efficiency parameters.
> Implement efficiency parameter equations for HeatExchanger class

- docs/modules/ude.rst
- docs/whats_new/v0-7-7.rst
> Fix deprecated section in docs on derivative placement in Jacobian

- docs/modules/networks.rst
- docs/whats_new/v0-7-7.rst
- src/tespy/networks/network.py
- tutorial/advanced/starting_values.py
> Make the topology simplification reset a public method

- docs/whats_new/v0-7-7.rst
- src/tespy/components/heat_exchangers/simple.py
- tests/test_analyses/test_exergy_analysis.py
- tests/test_models/test_CGAM_model.py
- tests/test_models/test_solar_energy_generating_system.py
> Change default value for dissipative to None

- README.rst
- docs/introduction.rst
> Update the introductory text and the feature list

- docs/whats_new/v0-7-9.rst
- src/tespy/components/reactors/water_electrolyzer.py
- src/tespy/networks/network.py
> Move the postprocessing behind the convergence check

- .github/workflows/packaging.yml
- .github/workflows/tox_checks.yml
- .github/workflows/tox_pytest.yml
- docs/whats_new.rst
- docs/whats_new/v0-7-10.rst
- src/tespy/components/combustion/diabatic.py
- src/tespy/components/combustion/engine.py
- src/tespy/components/component.py
- src/tespy/components/heat_exchangers/base.py
- src/tespy/components/heat_exchangers/simple.py
- src/tespy/components/piping/valve.py
- src/tespy/components/reactors/fuel_cell.py
- src/tespy/components/reactors/water_electrolyzer.py
- src/tespy/components/turbomachinery/base.py
- src/tespy/components/turbomachinery/compressor.py
- src/tespy/components/turbomachinery/pump.py
- src/tespy/components/turbomachinery/turbine.py
> Implement `dp` parameter for all components with `pr` parameter

- docs/whats_new/v0-8-0.rst
- src/tespy/networks/network.py
> Allow export to folder + csv file structure

- docs/whats_new.rst
- docs/whats_new/v0-8-1.rst
- src/tespy/networks/network.py
- tests/test_networks/test_network.py
> Include a check for missing fluid wrapper information

- docs/modules/components.rst
- docs/modules/networks.rst
- docs/whats_new/v0-8-2.rst
- src/tespy/components/component.py
- src/tespy/connections/connection.py
- src/tespy/networks/network.py
- tests/test_analyses/test_entropy_analysis.py
- tests/test_analyses/test_exergy_analysis.py
- tests/test_components/test_combustion.py
- tests/test_components/test_heat_exchangers.py
- tests/test_components/test_merge.py
- tests/test_components/test_piping.py
- tests/test_components/test_reactors.py
- tests/test_components/test_turbomachinery.py
- tests/test_models/test_CGAM_model.py
- tests/test_models/test_heat_pump_model.py
- tests/test_networks/test_binary_incompressible.py
- tests/test_networks/test_bypassing.py
- tests/test_networks/test_mixing_rules.py
- tests/test_networks/test_network.py
- tests/test_tools/test_fluid_properties/test_coolprop.py
- tests/test_tools/test_fluid_properties/test_iapws.py
- tests/test_tools/test_fluid_properties/test_pyromat.py
- tutorial/basics/gas_turbine.py
> Implement status variables for `solve` method

- docs/api/components.rst
- docs/modules/components.rst
- docs/references.bib
- docs/whats_new/v0-9-4.rst
- src/tespy/components/__init__.py
- src/tespy/components/component.py
- src/tespy/components/reactors/fuel_cell.py
- src/tespy/components/reactors/water_electrolyzer.py
- src/tespy/components/turbomachinery/base.py
- src/tespy/components/turbomachinery/compressor.py
- src/tespy/components/turbomachinery/polynomial_compressor.py
- src/tespy/components/turbomachinery/pump.py
- src/tespy/components/turbomachinery/steam_turbine.py
- src/tespy/components/turbomachinery/turbine.py
- tests/test_components/test_polynomial_compressor.py
This is a draft to add a new type of compressor. The class takes an `EN12900` polynome and can calulate the isentropic and volumetric efficiency based on https://www.sciencedirect.com/science/article/abs/pii/S1290072910001092. With those values fixed, you can simulate the effect of rpm on displacement and vice versa. It also allows to model dissipative heat loss.
> Add a PolynomialCompressor class

- docs/whats_new/v0-9-7.rst
- src/tespy/networks/network.py
- tests/test_tools/test_fluid_properties/test_coolprop.py
> Remove units for component printouts

- docs/whats_new/v0-9-7.rst
- pyproject.toml
- src/tespy/tools/units.py
> Put the pint cache in an expected location

- docs/whats_new/v0-9-8.rst
- pyproject.toml
- src/tespy/__init__.py
- src/tespy/connections/connection.py
- tests/test_connections.py
> Make the specification of pressure via bubble or dew line temperature possible

- docs/api/components.rst
- docs/modules/components.rst
- docs/references.bib
- docs/whats_new/v0-9-8.rst
- src/tespy/components/__init__.py
- src/tespy/components/heat_exchangers/movingboundary.py
- src/tespy/components/heat_exchangers/sectioned.py
- tests/test_components/test_heat_exchangers.py
Add a new component following the implementation idea here https://github.com/squoilin/NextGenerationHeatPumps: linear sections of enthalpy change and linear pressure difference over all sections.
> Add new component `SectionedHeatExchanger`
